### ISSUE TITLE
failed to resolve: could not find `std` in `{{root}}`

### ISSUE THREAD

**Issue by Valodim** [SpaceManiac/runtime-fmt#9]
Hi there,

thanks for your work on this crate :) I'm currently adding i18n to [Hagrid](https://gitlab.com/hagrid-keyserver/hagrid/), using the `gettext-macros` crate which internally uses `runtime-fmt`.  I'm running into this issue:

```
error[E0433]: failed to resolve: could not find `std` in `{{root}}`
   --> <::runtime_fmt::macros::rt_format macros>:4:25
    |
1   | / ($ ($ rest : tt) *) =>
2   | | {
3   | |     rt_format_args ! ($ ($ rest) *) . map
4   | |     (| x | x . with (:: std :: fmt :: format))
    | |                         ^^^ could not find `std` in `{{root}}`
5   | | }
    | |_- in this expansion of `rt_format!`
    | 
   ::: src/mail.rs:159:13
    |
159 |               i18n!(i18n.catalog, "Your key upload on {}"; self.domain),
    |               ---------------------------------------------------------
    |               |
    |  _____________in this macro invocation
    | |
160 | |             "welcome",
161 | |             i18n.lang,
162 | |             ctx,
...   |
    | 
   ::: /home/valodim/.cargo/registry/src/github.com-1ecc6299db9ec823/gettext-macros-0.5.2/src/lib.rs:462:1
    |
462 | / pub fn i18n(input: TokenStream) -> TokenStream {
463 | |     let span = input
464 | |         .clone()
465 | |         .into_iter()
...   |
527 | |     res
528 | | }
    | |_- in this expansion of `i18n!`
```

Failed build job is here: https://gitlab.com/hagrid-keyserver/hagrid/-/jobs/283292757

It's possible that this is a problem in gettext-macros or in my code, but the backtrace points to `runtime-fmt` and at a first glance I wouldn't know how this could be caused by us. Any ideas? :)

**Comment by SpaceManiac** [comment]
No obvious reason this shouldn't work.

If I'm understanding things, your 2015 edition crate is calling a 2018 edition proc_macro (`i18n!`) which is expanding to a call to a 2015 edition macro_rules (`rt_format!`). Module resolution differs between 2015 and 2018 editions so maybe there's some kind of rustc bug here?

**Comment by Valodim** [comment]
Phew. I'm a bit out of my depth with macros and that kind of compiler internals :) perhaps we can ping someone more knowledgeable about these topics?

**Comment by Valodim** [comment]
I was able to get this to work by updating my code to use 2018 edition. That'll work for me.

I guess we should escalate this bug somewhere? But I'm not sure where :) This is probably not something that runtime-fmt can do anything about, so feel free to close this bug.
